import 'dotenv/config';
import express, { Request, Response, NextFunction } from 'express';
import cors from 'cors'; import helmet from 'helmet'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import crypto from 'node:crypto'; import rateLimit from 'express-rate-limit'; import { z } from 'zod'; import { PrismaClient } from '@prisma/client';
const app=express(), db=new PrismaClient(); app.use(helmet()); app.use(cors({origin:process.env.CORS_ORIGIN?.split(',')||'*'})); app.use(express.json());
const accessSecret=process.env.JWT_ACCESS_SECRET!, refreshSecret=process.env.JWT_REFRESH_SECRET!;
const registerSchema=z.object({name:z.string().min(2).max(80),email:z.string().email().transform(v=>v.toLowerCase()),password:z.string().min(8).max(72)});
const loginSchema=z.object({email:z.string().email().transform(v=>v.toLowerCase()),password:z.string().min(1)});
const hash=(value:string)=>crypto.createHash('sha256').update(value).digest('hex');
function tokens(userId:string){const access=jwt.sign({sub:userId},accessSecret,{expiresIn:`${process.env.ACCESS_TOKEN_MINUTES||15}m`}); const refresh=jwt.sign({sub:userId},refreshSecret,{expiresIn:`${process.env.REFRESH_TOKEN_DAYS||7}d`}); return {access,refresh};}
app.get('/health',(_,res)=>res.json({ok:true,service:'auth-service'}));
const loginLimit=rateLimit({windowMs:15*60*1000,max:10,standardHeaders:true,legacyHeaders:false,message:{error:'Too many login attempts'}});
app.post('/register',async(req,res,next)=>{try{const input=registerSchema.parse(req.body); if(await db.user.findUnique({where:{email:input.email}})) return res.status(409).json({error:'Email already registered'}); const user=await db.user.create({data:{name:input.name,email:input.email,passwordHash:await bcrypt.hash(input.password,12)}}); const t=tokens(user.id); await db.refreshToken.create({data:{tokenHash:hash(t.refresh),userId:user.id,expiresAt:new Date(Date.now()+7*86400000)}}); res.status(201).json({user:{id:user.id,name:user.name,email:user.email},...t});}catch(e){next(e)}});
app.post('/login',loginLimit,async(req,res,next)=>{try{const input=loginSchema.parse(req.body),user=await db.user.findUnique({where:{email:input.email}}); if(!user||!(await bcrypt.compare(input.password,user.passwordHash))) return res.status(401).json({error:'Invalid email or password'}); const t=tokens(user.id); await db.refreshToken.create({data:{tokenHash:hash(t.refresh),userId:user.id,expiresAt:new Date(Date.now()+7*86400000)}}); res.json({user:{id:user.id,name:user.name,email:user.email},...t});}catch(e){next(e)}});
app.post('/refresh',async(req,res,next)=>{try{const parsed=z.object({refreshToken:z.string()}).parse(req.body); const p=jwt.verify(parsed.refreshToken,refreshSecret) as {sub:string}; const row=await db.refreshToken.findUnique({where:{tokenHash:hash(parsed.refreshToken)}}); if(!row||row.expiresAt<new Date()) return res.status(401).json({error:'Refresh token expired'}); const t=tokens(p.sub); await db.$transaction([db.refreshToken.delete({where:{id:row.id}}),db.refreshToken.create({data:{tokenHash:hash(t.refresh),userId:p.sub,expiresAt:new Date(Date.now()+7*86400000)}})]); res.json(t);}catch(e){res.status(401).json({error:'Invalid refresh token'})}});
app.get('/verify',async(req,res)=>{try{const value=req.headers.authorization?.replace('Bearer ',''); if(!value) return res.status(401).json({error:'Missing token'}); const p=jwt.verify(value,accessSecret) as {sub:string}; const user=await db.user.findUnique({where:{id:p.sub},select:{id:true,name:true,email:true}}); if(!user)return res.status(401).json({error:'User not found'}); res.json({user});}catch{res.status(401).json({error:'Invalid token'})}});
app.use((e:unknown,_req:Request,res:Response,_next:NextFunction)=>{if(e instanceof z.ZodError)return res.status(400).json({error:'Validation failed',details:e.flatten()}); console.error(e);res.status(500).json({error:'Internal server error'})});
const port=Number(process.env.PORT||5000); app.listen(port,()=>console.log(`Auth service listening on ${port}`));
