import { FormEvent, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

type Product = { id: string; name: string; sku: string; price: string | number; stock: number };
type Customer = { id: string; name: string; phone?: string; balance: string | number };
const authUrl = import.meta.env.VITE_AUTH_URL || 'http://localhost:5000';
const api = import.meta.env.VITE_API_URL || 'http://localhost:5001';

function App() {
  const [token, setToken] = useState(localStorage.getItem('accessToken') || '');
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  const [tab, setTab] = useState('dashboard'); const [dashboard, setDashboard] = useState<any>({}); const [products, setProducts] = useState<Product[]>([]); const [customers, setCustomers] = useState<Customer[]>([]); const [sales, setSales] = useState<any[]>([]);
  const [product, setProduct] = useState({ name: '', sku: '', price: '', stock: '' }); const [customer, setCustomer] = useState({ name: '', phone: '' }); const [sale, setSale] = useState({ productId: '', quantity: '1', customerId: '', paid: '' });
  const request = async (path: string, options: RequestInit = {}) => { const response = await fetch(`${api}${path}`, { ...options, headers: { 'content-type': 'application/json', authorization: `Bearer ${token}`, ...(options.headers || {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Request failed'); return body; };
  const load = async () => { try { const [d, p, c, s] = await Promise.all([request('/api/dashboard'), request('/api/products'), request('/api/customers'), request('/api/sales')]); setDashboard(d); setProducts(p); setCustomers(c); setSales(s); } catch (e: any) { setError(e.message); } };
  useEffect(() => { if (token) load(); }, [token]);
  async function login(e: FormEvent) { e.preventDefault(); try { const response = await fetch(`${authUrl}/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); localStorage.setItem('accessToken', body.access); setToken(body.access); } catch (e: any) { setError(e.message); } }
  async function addProduct(e: FormEvent) { e.preventDefault(); try { await request('/api/products', { method: 'POST', body: JSON.stringify({ ...product, price: Number(product.price), stock: Number(product.stock) }) }); setProduct({ name: '', sku: '', price: '', stock: '' }); load(); } catch (e: any) { setError(e.message); } }
  async function addCustomer(e: FormEvent) { e.preventDefault(); try { await request('/api/customers', { method: 'POST', body: JSON.stringify(customer) }); setCustomer({ name: '', phone: '' }); load(); } catch (e: any) { setError(e.message); } }
  async function addSale(e: FormEvent) { e.preventDefault(); try { await request('/api/sales', { method: 'POST', body: JSON.stringify({ productId: sale.productId, quantity: Number(sale.quantity), customerId: sale.customerId || null, paid: Number(sale.paid || 0), items: [{ productId: sale.productId, quantity: Number(sale.quantity) }] }) }); setSale({ productId: '', quantity: '1', customerId: '', paid: '' }); load(); setTab('sales'); } catch (e: any) { setError(e.message); } }
  if (!token) return <main className="login card"><h1>Dukaan ERP</h1><p>Simple shop management</p><form onSubmit={login}><input placeholder="Email" type="email" value={email} onChange={e => setEmail(e.target.value)} required /><input placeholder="Password" type="password" value={password} onChange={e => setPassword(e.target.value)} required /><button>Login</button></form><small>{error}</small></main>;
  return <main><header><div><h1>Dukaan ERP</h1><p className="muted">Inventory, billing and udhaar</p></div><button className="secondary" onClick={() => { localStorage.removeItem('accessToken'); setToken(''); }}>Logout</button></header><nav>{['dashboard', 'products', 'customers', 'sales'].map(item => <button className={tab === item ? 'active' : 'secondary'} onClick={() => setTab(item)} key={item}>{item[0].toUpperCase() + item.slice(1)}</button>)}</nav>{error && <div className="alert">{error}<button onClick={() => setError('')}>×</button></div>}{tab === 'dashboard' && <><section className="grid">{[['Products', dashboard.products], ['Customers', dashboard.customers], ['Sales', dashboard.sales], ['Stock units', dashboard.stock], ['Revenue', `₹${dashboard.revenue || 0}`]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value ?? '...'}</strong></article>)}</section><section className="card"><h2>Quick sale</h2><SaleForm products={products} customers={customers} sale={sale} setSale={setSale} submit={addSale} /></section></>}{tab === 'products' && <section className="card"><h2>Products</h2><form className="form-grid" onSubmit={addProduct}>{Object.keys(product).map(key => <input key={key} placeholder={key[0].toUpperCase() + key.slice(1)} value={(product as any)[key]} type={key === 'price' || key === 'stock' ? 'number' : 'text'} onChange={e => setProduct({ ...product, [key]: e.target.value })} required />)}<button>Add product</button></form><Table headers={['Name', 'SKU', 'Price', 'Stock']} rows={products.map(p => [p.name, p.sku, `₹${p.price}`, p.stock])} /></section>}{tab === 'customers' && <section className="card"><h2>Customers & udhaar</h2><form className="form-grid" onSubmit={addCustomer}><input placeholder="Name" value={customer.name} onChange={e => setCustomer({ ...customer, name: e.target.value })} required /><input placeholder="Phone" value={customer.phone} onChange={e => setCustomer({ ...customer, phone: e.target.value })} /><button>Add customer</button></form><Table headers={['Name', 'Phone', 'Outstanding']} rows={customers.map(c => [c.name, c.phone || '-', `₹${c.balance}`])} /></section>}{tab === 'sales' && <section className="card"><h2>New sale</h2><SaleForm products={products} customers={customers} sale={sale} setSale={setSale} submit={addSale} /><Table headers={['Date', 'Customer', 'Total', 'Paid']} rows={sales.map(s => [new Date(s.createdAt).toLocaleString(), s.customer?.name || 'Cash', `₹${s.total}`, `₹${s.paid}`])} /></section>}</main>;
}
function SaleForm({ products, customers, sale, setSale, submit }: any) { return <form className="form-grid" onSubmit={submit}><select value={sale.productId} onChange={e => setSale({ ...sale, productId: e.target.value })} required><option value="">Select product</option>{products.map((p: Product) => <option value={p.id} key={p.id}>{p.name} ({p.stock} in stock)</option>)}</select><input type="number" min="1" placeholder="Quantity" value={sale.quantity} onChange={e => setSale({ ...sale, quantity: e.target.value })} required /><select value={sale.customerId} onChange={e => setSale({ ...sale, customerId: e.target.value })}><option value="">Cash sale</option>{customers.map((c: Customer) => <option value={c.id} key={c.id}>{c.name}</option>)}</select><input type="number" min="0" step="0.01" placeholder="Paid amount" value={sale.paid} onChange={e => setSale({ ...sale, paid: e.target.value })} required /><button>Complete sale</button></form> }
function Table({ headers, rows }: { headers: string[]; rows: any[][] }) { return <div className="table-wrap"><table><thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>) : <tr><td colSpan={headers.length}>No records yet</td></tr>}</tbody></table></div> }
createRoot(document.getElementById('root')!).render(<App />);
