import 'dotenv/config'; import express,{Request,Response,NextFunction} from 'express'; import cors from 'cors'; import helmet from 'helmet'; import {z} from 'zod'; import {PrismaClient} from '@prisma/client';
const app=express(),db=new PrismaClient(); app.use(helmet());app.use(cors({origin:process.env.CORS_ORIGIN?.split(',')||'*'}));app.use(express.json());
async function auth(req:Request,res:Response,next:NextFunction){try{const token=req.headers.authorization; if(!token)return res.status(401).json({error:'Missing authorization'}); const r=await fetch(`${process.env.AUTH_SERVICE_URL}/verify`,{headers:{authorization:token}}); if(!r.ok)return res.status(401).json({error:'Unauthorized'}); (req as any).user=(await r.json()).user;next()}catch{res.status(503).json({error:'Auth service unavailable'})}}
const product=z.object({name:z.string().min(1).max(120),sku:z.string().min(1).max(40),price:z.coerce.number().nonnegative(),stock:z.coerce.number().int().nonnegative()}); const customer=z.object({name:z.string().min(1).max(120),phone:z.string().optional()});
app.get('/health',(_,r)=>r.json({ok:true,service:'main-backend'})); app.use('/api',auth);
app.get('/api/products',async(_,r,n)=>{try{r.json(await db.product.findMany({orderBy:{createdAt:'desc'}}))}catch(e){n(e)}}); app.post('/api/products',async(req,r,n)=>{try{r.status(201).json(await db.product.create({data:product.parse(req.body)}))}catch(e){n(e)}});
app.get('/api/customers',async(_,r,n)=>{try{r.json(await db.customer.findMany({orderBy:{createdAt:'desc'}}))}catch(e){n(e)}}); app.post('/api/customers',async(req,r,n)=>{try{r.status(201).json(await db.customer.create({data:customer.parse(req.body)}))}catch(e){n(e)}});
app.get('/api/dashboard',async(_,r,n)=>{try{const [products,customers,sales]=await Promise.all([db.product.count(),db.customer.count(),db.sale.aggregate({ _sum:{total:true}})]);r.json({products,customers,revenue:sales._sum.total||0})}catch(e){n(e)}});
app.use((e:unknown,_q:Request,r:Response,_n:NextFunction)=>{if(e instanceof z.ZodError)return r.status(400).json({error:'Validation failed',details:e.flatten()});console.error(e);r.status(500).json({error:'Internal server error'})}); app.listen(Number(process.env.PORT||5001),()=>console.log('Main backend listening'));
